### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Elinore88** [VanHeise/mevbot#3]
Is it possible to have such a profit as Jaredfromsubway? I see his balance on April 14 was 5 ETH. And now more than 250 ETH
![jared](https://github.com/VanHeise/mevbot/assets/132002488/8a363ec5-4318-44bf-9dcc-eccf236dd410)

**Comment by VanHeise** [comment]
I think the balance was initially large. You just see the ETH token on the chart, and the rest of the funds were in different tokens (low-liquid), probably for profit. Jaredfromsubway is now one of the leaders in the race for GAS
I think my answer will suit you. I will close)
